[package]
name = "downr/replicator"
version = "0.1.0"
description = "Table-based replication library for shared data."
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Downrest/Replicator"
realm = "shared"

[dependencies]
Signal = "nowoshire/namedsignal@^"
DeltaCompress = "nezuo/delta-compress@^"
t = "osyrisrblx/t@^"