[package]
name = "downrest/replicator"
version = "1.0.1"
description = "Table-based replication library for shared data."
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Downrest/Replicator"
realm = "shared"

[dependencies]
Signal = "nowoshire/namedsignal@^2.3.3"
DeltaCompress = "nezuo/delta-compress@^0.1.3"
t = "osyrisrblx/t@^3.1.1"